# deploy
app_container_name: en-core-app
app_image_tag: 0.3.0
app_image_name: denbon05/en-core
container_state: started

# notification
app_gmail: langcoresender@gmail.com
support_email: langcoresender@gmail.com
