version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://en_core:supersecret@db:5432/en_core
    ports:
      - 3000:8000
    volumes:
      - ./app:/app
    command: bash -c 'sleep 3 && make db-latest && make start'
    depends_on:
      - db

  db:
    image: postgres:15.2
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: en_core
      TZ: Europe/Warsaw
