version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      platforms:
        - 'linux/amd64'
    image: denbon05/en-core
    command: bash -c 'sleep 3 && npm test'
    env_file: ./app/.env
