import './init';
import appMode from './mode';

const {
  GOOGLE_API_KEY,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI_PROD,
  JWT_SECRET,
  NODE_ENV,
  INITIALIZATION_VECTOR,
  CIPHER_KEY,
} = process.env;

const GOOGLE_REDIRECT_URI_DEV =
  'http://localhost:3000/api/google/oauth2callback';

const GOOGLE_REDIRECT_URI = appMode.isProd()
  ? GOOGLE_REDIRECT_URI_PROD
  : GOOGLE_REDIRECT_URI_DEV;

export {
  NODE_ENV,
  GOOGLE_API_KEY,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
  JWT_SECRET,
  INITIALIZATION_VECTOR,
  CIPHER_KEY,
};
