# project
app_mode: dev
app_path: "../../../" # relative for 'playbook' dir

# database
db_container_name: en_core_db
db_container_state: started
db_port_dev: 5431
db_port_test: 5430
db_pass: supersecret
db_user: en_core
db_name: en_core
pg_version: "14.7-alpine"

# vars
jwt_secret: "good_day"
google_auth_filename: ".gauth.json"
