---
- name: Deploy app
  hosts: webservers
  gather_facts: true

  tasks:
    - name: Add vars for the app
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.template', 'env.j2') }}"
        insertbefore: 'BOF'
        path: './.env'
        mode: '0644'
        owner: '{{ ansible_env.USER }}'
        create: true

    - name: Retrieve app exposed port
      ansible.builtin.command: "grep -oP '(?<=EXPOSE.)\\d+' {{ app_dirpath }}/Dockerfile.prod"
      register: prod_dockerfile
      delegate_to: localhost
      changed_when: container_state == 'started'

    - name: Manage docker app
      community.docker.docker_container:
        name: '{{ app_container_name }}'
        image: '{{ app_image_name }}:{{ app_image_tag }}'
        restart_policy: unless-stopped
        state: '{{ container_state }}'
        ports:
          - '{{ app_port }}:{{ prod_dockerfile.stdout }}'
        env_file: ./.env
