---
- name: Deploy app
  hosts: webservers
  gather_facts: true

  tasks:
    - name: Add vars for the app
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.template', 'env.j2') }}"
        insertbefore: 'BOF'
        path: '{{ app_dirpath }}/.env'
        mode: '0644'
        owner: '{{ ansible_env.USER }}'
        create: true

    - name: Manage docker app
      community.docker.docker_container:
        name: '{{ app_container_name }}'
        image: '{{ image_with_tag }}'
        restart_policy: always
        state: '{{ container_state }}'
        ports:
          - '{{ app_port }}:{{ app_port }}'
        env_file: /.env
