---
- name: Deploy app
  hosts: webservers
  gather_facts: true

  tasks:
    - name: Add vars for project
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.template', 'env.j2') }}"
        insertbefore: 'BOF'
        path: '{{ app_dirpath }}/.env'
        mode: '0644'
        owner: '{{ ansible_env.USER }}'
        create: true
