all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    webservers:
# BEGIN ANSIBLE MANAGED BLOCK
      hosts:
        web-server-1:
          ansible_host: 3.66.235.46
          ansible_user: ubuntu


# END ANSIBLE MANAGED BLOCK
