---
all:
  children:
    dev:
      hosts:
        localhost:
          ansible_connection: local

    test:
      hosts:
        localhost:
          ansible_connection: local

    db:
      children:
        dev:
        test:
