---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    webservers:
# BEGIN ANSIBLE MANAGED BLOCK
      hosts:
        web-server-1:
          ansible_host: 3.122.54.103
          ansible_user: ubuntu
        web-server-2:
          ansible_host: 52.59.248.169
          ansible_user: ubuntu
# END ANSIBLE MANAGED BLOCK

    database:
      children:
        local:
