---
- name: Init project
  hosts: local

  tasks:
    - name: Init local variables
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.template', 'env.dev.j2') }}"
        path: '{{ app_dirpath }}/.env'
        insertbefore: 'BOF'
        mode: '0644'
        owner: '{{ ansible_env.USER }}'
        create: true

    - name: Define db version
      ansible.builtin.replace:
        path: '{{ app_dirpath }}/docker-compose.override.yml'
        regexp: 'image: .*'
        replace: 'image: {{ db.engine }}:{{ db.version }}'
