---
- name: Prepare environment on servers
  hosts: webservers
  gather_facts: true
  become: true

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install apt packages
      ansible.builtin.apt:
        state: present
        pkg:
          - postgresql-client

    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip
