---
- name: Prepare environment on servers
  hosts: webservers
  gather_facts: true
  become: true

  roles:
    - role: geerlingguy.docker
      docker_users:
        - '{{ ansible_env.USER }}'

  tasks:
    - name: Allow docker.sock access
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0666'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install apt packages
      ansible.builtin.apt:
        state: present
        pkg:
          - postgresql-client
          - python3-pip
