---
- name: Init database
  hosts: local
  gather_facts: true
  become: true

  roles:
    - role: geerlingguy.postgresql
      postgresql_user: postgres
      postgresql_group: postgres
      postgresql_databases:
        - name: '{{ db_name }}'
          owner: '{{ db_user }}'
          state: '{{ db_state }}'
      postgresql_users:
        - name: '{{ db_user }}'
          password: '{{ db_user_pass }}'
          role_attr_flags: CREATEDB,NOSUPERUSER
      postgresql_hba_entries:
        - { type: local, database: all, user: all, auth_method: trust }
        - {
            type: host,
            database: all,
            user: all,
            address: '127.0.0.1/32',
            auth_method: md5,
          }
        - {
            type: host,
            database: all,
            user: all,
            address: '::1/128',
            auth_method: md5,
          }
