---
- name: Setup project vars
  hosts: local
  gather_facts: true

  tasks:
    - name: Add vars for project
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.template', '../templates/env.j2') }}"
        insertbefore: 'BOF'
        path: '{{ app_path }}/.env'
        mode: '0644'
        owner: '{{ ansible_env.USER }}'
        create: true

    - name: Manage explicite github action vars
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.template', '../templates/db-workflow.yml.j2') }}"
        mode: '0644'
        path: '{{ app_path }}/.github/workflows/database.yml'
        insertafter: 'image:'
