#!/usr/bin/env node
// @ts-check
const { execSync } = require('child_process');

const checkVaultEncrypted = () => {
  const arg = process.argv[2];
  console.warn('Going to check decrypted files, one sec 👀');
  const vaultFiles = execSync(`find ${arg ?? 'ansible'} -name "*vault.y*ml"`)
    .toString()
    .split('\n')
    .filter(Boolean);

  const encryptedPattern = /\$ANSIBLE_VAULT;/;
  const decryptedFiles = [];
  for (const vaultFile of vaultFiles) {
    const output = execSync(`head -n 1 ${vaultFile}`).toString();
    const isFileDecrypted = !encryptedPattern.test(output);

    if (isFileDecrypted) {
      decryptedFiles.push(vaultFile);
    }
  }

  if (decryptedFiles.length) {
    console.error(
      `Forgot to encrypt something 💀?\n${decryptedFiles.join('\n')}`,
    );
    process.exit(1);
  }
};

checkVaultEncrypted();

console.info('Everything seems cool 🤙');
process.exit(0);
