name: Build app

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed

defaults:
  run:
    working-directory: ./en-core

env:
  APP_IMAGE_NAME: denbon05/en-core

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: DEBUG
        run: pwd

      - name: Extract app version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.2.1
        with:
          path: '${{ github.workspace }}/en-core'

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '${{ github.workspace }}/en-core'
          file: '${{ github.workspace }}/en-core/Dockerfile.prod'
          push: true
          tags: '${{ env.APP_IMAGE_NAME }}:${{ steps.extract_version.outputs.version }}'
