name: CD

on:
  workflow_run:
    workflows:
      - Build app
    branches:
      - main
    types:
      - completed

defaults:
  run:
    working-directory: ./en-core

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS
        run: |
          echo TODO
